// <auto-generated />
namespace Cinema.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class majorchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(majorchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202105271841195_major-changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
