// <auto-generated />
namespace Cinema.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nothing_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nothing_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202105261905178_nothing_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
